### ISSUE TITLE
Docker install headless browser

### ISSUE THREAD

**Issue by rafalohaki** [m1guelpf/chatgpt-telegram#80]
```
2022/12/14 11:59:31 Couldn't get OpenAI session: Couldn't install headless browser: could not install driver: could not install browsers: could not install browsers: exit status 127
2022/12/14 11:59:48 Couldn't get OpenAI session: Couldn't install headless browser: could not install driver: could not install driver: could not check if driver is up2date: could not run driver: exit status 127
/root/.cache/ms-playwright-go/1.20.0-beta-1647057403000/playwright.sh: line 3: /root/.cache/ms-playwright-go/1.20.0-beta-1647057403000/node: not found
2022/12/14 11:59:31 Downloaded driver successfully
2022/12/14 11:59:27 Downloading driver to /root/.cache/ms-playwright-go/1.20.0-beta-1647057403000
```

**Comment by davidanger** [comment]
Any solution?

**Comment by wshopcode** [comment]
I have this issue too. I wonder if it's because I am running Windows 7

**Comment by sebaplaza** [comment]
You're using the official docker image ?

```
ghcr.io/m1guelpf/chatgpt-telegram
```

Can you give more details ?

OS (if windows, using wsl?), docker parameters, etc

**Comment by wshopcode** [comment]
> You're using the official docker image ?
> 
> ```
> ghcr.io/m1guelpf/chatgpt-telegram
> ```
> 
> Can you give more details ?
> 
> OS (if windows, using wsl?), docker parameters, etc

UPDATE: I managed to get passed this somehow. I got everything working but then I couldn't log into ChatGpt. Chromium kept popping up with this "chrome is being controlled by automated test software". Cloudflare couldn't authenticate me since it wasn't detecting a human but a bot. I gave up at that point.

**Comment by ChrisToxz** [comment]
Same issue here.
```
chatgpt-telegram    | 2022/12/27 16:47:18 Downloading driver to /root/.cache/ms-playwright-go/1.20.0-beta-1647057403000
chatgpt-telegram    | 2022/12/27 16:47:20 Downloaded driver successfully
chatgpt-telegram    | /root/.cache/ms-playwright-go/1.20.0-beta-1647057403000/playwright.sh: line 3: /root/.cache/ms-playwright-go/1.20.0-beta-1647057403000/node: not found
chatgpt-telegram    | 2022/12/27 16:47:20 Couldn't get OpenAI session: Couldn't install headless browser: could not install driver: could not install browsers: could not install browsers: exit status 127
```

**OS:** Proxmox -> Debian -> Docker

**docker-compose.yml**
```
services:
  chatgpt-telegram:
    image: ghcr.io/m1guelpf/chatgpt-telegram:latest
    container_name: chatgpt-telegram
    volumes:
      # your ".config" local folder must include a "chatgpt.json" file
      - .config/:/root/.config
      - .cache/:/root/.cache
    environment:
      - TELEGRAM_ID=
      - TELEGRAM_TOKEN=
```

I added .cache folder to volumes to double check the following error `/root/.cache/ms-playwright-go/x/playwright.sh: line 3: /root/.cache/ms-playwright-go/x/node: not found` 
But the node file does exists.

No proxy in my network, as that was a suggested solution in another issue.
